title: William D. Lukito
tagline: Ph.D. Candidate, AI for IoT Satellite Communications
description: Personal website of William D. Lukito
url: "https://wdloe.github.io"
baseurl: "" # Important for GitHub Pages

theme: jekyll-theme-chirpy

lang: en
timezone: Australia/Melbourne

author:
  name: William D. Lukito
  email: W.Lukito@latrobe.edu.au
  links:
    - https://github.com/wdloe
    - https://www.linkedin.com/in/williamdlukito

# Plugins required by Chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Optional features
toc: true
mode: light